version: '2'
services:
    craft-app:
        image: craft
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://craft-mysql:3306/craft?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    craft-mysql:
        extends:
            file: mysql.yml
            service: craft-mysql
